kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dirserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dirserver
    spec:
      containers:
      - name: dirserver
        image: gcr.io/PROJECT/dirserver
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /dirserver-logs
          name: dirserver-logs
      volumes:
      - name: dirserver-logs
        gcePersistentDisk:
          pdName: dirserver-logs
          fsType: ext4
