kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: keyserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keyserver
    spec:
      containers:
      - name: keyserver
        image: gcr.io/PROJECT/keyserver
        ports:
        - containerPort: 80
        - containerPort: 443
