kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: userserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: userserver
    spec:
      containers:
      - name: userserver
        image: gcr.io/PROJECT/userserver
        ports:
        - containerPort: 80
        - containerPort: 443
